Repository I-Taxi/itaxi-server, pull requests merged in 2022-07, with the labels that each got.

#12 [#7] NOTICE 관련 API 개발
  src/main/java/com/itaxi/server/docs/ApiDoc.java
  src/main/java/com/itaxi/server/exception/Message.java
  src/main/java/com/itaxi/server/exception/notice/NoticeContentEmptyException.java
  src/main/java/com/itaxi/server/exception/notice/NoticeTitleEmptyException.java
  src/main/java/com/itaxi/server/notice/application/NoticeService.java
  src/main/java/com/itaxi/server/notice/application/dto/NoticeCreateDto.java
  src/main/java/com/itaxi/server/notice/application/dto/NoticeUpdateDto.java
  src/main/java/com/itaxi/server/notice/domain/Notice.java
  src/main/java/com/itaxi/server/notice/presentation/NoticeController.java
  src/main/java/com/itaxi/server/notice/presentation/request/NoticeCreateRequest.java
  src/main/java/com/itaxi/server/notice/presentation/request/NoticeUpdateRequest.java
  src/main/java/com/itaxi/server/notice/presentation/response/NoticeReadAllResponse.java
  src/main/java/com/itaxi/server/notice/presentation/response/NoticeReadResponse.java
Labels: feat, api

#17 [#16] : 도커 빌드 스크립트 작성 및 서버 배포 환경설정
  Dockerfile
  docker-compose.yml
Labels: feat

#19 [#18] : 컨트롤러 경로수정
  src/main/java/com/itaxi/server/member/presentation/MemberController.java
  src/main/java/com/itaxi/server/place/presentation/PlaceController.java
Labels: fix

#42 feat[#41] : Notice API 조회수 증가 기능 추가
  src/main/java/com/itaxi/server/docs/ApiDoc.java
  src/main/java/com/itaxi/server/notice/application/NoticeService.java
  src/main/java/com/itaxi/server/notice/presentation/NoticeController.java
  src/main/java/com/itaxi/server/post/presentation/PostController.java
Labels: feat
